---
name: test_rule
description: test rule
enabled: true

trigger:
  type: aytrastorm.aytra_trigger

criteria:
  trigger.rule:
    type: "equals"
    pattern: "rule1"
    

action:
  ref: aytrastorm.example_action